### ISSUE TITLE
Poner los pesos de YOLO en un server aparte y bajarlos al comienzo de la app si es necesasrio

### ISSUE THREAD

**Issue by facundoq** [midusi/cctv_analysis#1]
agregar el archivo a gitignore

**Comment by tomasbarron** [comment]
Se agrego en el archivo Readme las instrucciones donde se especifica la pagina oficial con los pesos disponibles de Yolov3 y ademas para tener un backup se subio un link de google drive donde se encuentran los mismos pesos.
