### ISSUE TITLE
Poder hacer un request http adjuntando un video para llamar a la app  (sin navegador)

### ISSUE THREAD

**Issue by facundoq** [midusi/cctv_analysis#10]
Tener un client_example.py de prueba que utilice un request.

**Comment by tomasbarron** [comment]
Listo, retorna json con la informacion

**Comment by facundoq** [comment]
Hacer único el nombre de archivo de la respuesta.

**Comment by tomasbarron** [comment]
Se hizo unico el nombre del json utilizando el mismo nombre que usan los videos (generado con uuid), para de paso relacionar el video analizado con el archivo de salida
