### ISSUE TITLE
Eliminar pasos de configuración del proyecto

### ISSUE THREAD

**Issue by facundoq** [midusi/cctv_analysis#13]
Automatizar la descarga de los modelos, posiblemente guardando ya los modelos convertidos a formato Keras

 Si es necesario guardar archivos grandes (>100mb) vemos de armar un drive o equivalente para subirlo

**Comment by tomasbarron** [comment]
No hace falta configurar el proyecto, lo que si es necesesario cargar el archivo .h5 (237mb) en la carpeta cfg para el modelo de keras, en el caso del modelo de opencv requiere cargar los pesos (weights =237mb, tiny_weights= 34mb) en la carpeta weights
