### ISSUE TITLE
API asincrónica

### ISSUE THREAD

**Issue by facundoq** [midusi/cctv_analysis#19]
1) El cliente levanta un servidor para recibir los resultados en URL_RESPUESTA
2) El cliente hace un pedido de procesamiento asincrónico con una URL_RESPUESTA.
3) El servidor recibe el pedido, y el procesamiento pasa a un thread de background con un [Process](https://docs.python.org/3/library/multiprocessing.html). Se retorna un UUID para identificar el pedido y ahí termina el request. 
4) El servidor terminar de procesar el video. Hace un request de tipo GET a URL_RESPUESTA, con el resultado del procesamiento y el UUID para identificar el mismo.
5) El cliente procesa los resultados según sea necesario.

**Comment by facundoq** [comment]
Pseudocodigo servidor:

````python
def analizar(video,uuid,url):
    resultado = analizar_video(video)
    hacer_request("GET",url, params=(resultado,uuid))


def request(video,uuid,url)
    p = Process(target=analizar, args=(video,uuid,url))
    p.start()
````

**Comment by tomasbarron** [comment]
Se resolvio pero en lugar de pasar el resultado como parametros en una request GET, se paso el json en un request POST que se ve asi
    resultado  = {
        'peoplePerFrame': listaDePersonasPorFrame),
        'requestID': filename
    } 

el servidor cliente se corre desde run_client.py y para poder simular un pedido asincronico se separo en un archivo llamado client_request.py el pedido al servidor del modelo
