### ISSUE TITLE
Hacer refactoring de los modelos

### ISSUE THREAD

**Issue by facundoq** [midusi/cctv_analysis#9]
* separar carga/ejecución
````
model = models.load("nombre")
...
results = model.evaluate(video)
````

* ordenar la carga de cfgs
* quitar archivos extra tipo train/train_bottleneck
* pasar debug a un script

**Comment by tomasbarron** [comment]
Se ordeno carga de cfgs y se quito los archivos extra
falta separar carga/ejecucion

**Comment by facundoq** [comment]
Agregar una clase DetectionModel que tiene un método abstracto `detect` que recibe un video y devuelve la info
Agregar subclases YoloDetectionModel y OpenCVDetectionModel model para tener unificada la API de detección entre los dos.
